infer_args:
    # Data args
    dataset_path: ../utc/dataset/data
    label_file: ../label_studio_data/text_classification_labels.txt
    max_seq_len: 768
    last_index: 768

    # Model args
    schema: ["原告年齡", "肇事過失責任比例", "受有傷害"]
    utc_model_name_or_path: checkpoints/utc
    uie_model_name_or_path: ../uie/checkpoints/uie
    output_path: ../utc/dataset/uie_processed_data
    precision: fpew
    threshold: 0.4
    dynamic_adjust_length: True
    